### ISSUE TITLE
Missing API key: The library uses the `k` param instead of the X-WPT-API-KEY header

### ISSUE THREAD

**Issue by rejhgadellaabsl** [catchpoint/WebPageTest.api-nodejs#185]
As noted on the WebPageTest website: 

> API keys are now required in the X-WPT-API-KEY header. The query parameter k= will be ignored
> https://www.webpagetest.org/

Looks like this library wasn't updated to reflect this requirement.

```javascript
const wpt = new WebPageTest( 'www.webpagetest.org', '{ API-KEY }' );
wpt.runTestAndWait( url, options );
```

Result

```javascript
{
  statusCode: 400,
  statusText: 'An error occurred processing your request (missing API key). If you do not have an API key you can purchase one here: https://product.webpagetest.org/api'
}
```

Inspecting the options that are passed to [`protocol.get()`](https://github.com/catchpoint/WebPageTest.api-nodejs/blob/master/lib/webpagetest.js#L104), it turns out that the API key is passed as a query parameter:

```javascript
{
  path: '/runtest.php?url={ URL }&location=gce-europe-west4.Cable&connectivity=Cable&runs=1&fvonly=1&label={ LABEL }&keepua=1&lighthouse=0&f=json&k={ API-KEY }', 
  // ☝️⚠️ API key is passed as a query parameter here
  host: 'www.webpagetest.org',
  auth: null, // 👈 should this be null?
  port: 80,
  headers: {
    'accept-encoding': 'gzip,deflate',
    'User-Agent': 'WebpagetestNodeWrapper/v0.6.0'
    // ⚠️No X-WPT-API-KEY header here
  }
}
```

**Comment by lbartoli79** [comment]
Which version of the library are you using?

**Comment by rejhgadellaabsl** [comment]
Ah sorry, forgot that. We're using the latest version available on npm:

`webpagetest@0.7.1`

**Comment by lbartoli79** [comment]
Sorry we had a problem with our release process, we should be able to publish an updated package shortly

**Comment by claud-io** [comment]
@rejhgadellaabsl can you please try to update to v0.7.3? thanks.

**Comment by rejhgadellaabsl** [comment]
Just ran `npm outdated`:

```
Package          Current  Wanted  Latest
webpagetest        0.7.1   0.7.3   0.7.3
```

And looks like 0.7.3 fixed the issue! Thanks!
